# Fonts
font_family      family="JetBrainsMono Nerd Font Mono" style=Regular
bold_font        family="JetBrainsMono Nerd Font Mono" style=Bold
italic_font      family="JetBrainsMono Nerd Font Mono" style=Italic
bold_italic_font family="JetBrainsMono Nerd Font Mono" style="Bold Italic"
font_size 18.0

# Colors
background #000000
foreground #ffffff
background_opacity 1.0

# Scrolling
scrollback_lines 10000
wheel_scroll_multiplier 3.0
touch_scroll_multiplier 3.0

# Window
startup_session startup.session
